branch-protection:
  orgs:
    stolostron:
      repos:
        prometheus:
          branches:
            main:
              protect: true
            release-2.5:
              protect: true
              required_pull_request_reviews:
                required_approving_review_count: 1
            release-2.6:
              protect: true
              required_pull_request_reviews:
                required_approving_review_count: 1
            release-2.7:
              protect: true
              required_pull_request_reviews:
                required_approving_review_count: 1
            release-2.8:
              protect: false
          enforce_admins: true
          required_pull_request_reviews:
            dismiss_stale_reviews: false
          required_status_checks:
            contexts:
            - ci/prow/common-test
            - ci/prow/images
            - ci/prow/react-app-test
            - ci/prow/sonar-pre-submit
            - ci/prow/vendor
tide:
  merge_method:
    stolostron/prometheus: squash
