approve:
- commandHelpLink: ""
  repos:
  - stolostron/siteconfig
  require_self_approval: false
lgtm:
- repos:
  - stolostron/siteconfig
  review_acts_as_lgtm: true
plugins:
  stolostron/siteconfig: {}
