base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: ubi8-openjdk-11
    namespace: openshift
    tag: "1.12"
images:
- dockerfile_path: Dockerfile.autotune
  from: base
  to: autotune
promotion:
  disabled: true
  name: "2.9"
  namespace: stolostron
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: git-fast-forward
  postsubmit: true
  steps:
    env:
      DESTINATION_BRANCH: release-2.9
    workflow: ocm-ci-fastforward
- as: pr-image-mirror
  steps:
    dependencies:
      SOURCE_IMAGE_REF: autotune
    env:
      IMAGE_REPO: autotune
      REGISTRY_ORG: stolostron
    workflow: ocm-ci-image-mirror
- as: publish
  postsubmit: true
  steps:
    dependencies:
      SOURCE_IMAGE_REF: autotune
    env:
      IMAGE_REPO: autotune
      REGISTRY_ORG: stolostron
    test:
    - as: publish
      commands: |-
        export SELF="make -f /opt/build-harness/Makefile.prow"
        export OSCI_PUBLISH_DELAY="0"
        export OSCI_COMPONENT_NAME="autotune"
        export OSCI_COMPONENT_VERSION="2.9"
        make -f /opt/build-harness/Makefile.prow osci/publish
      credentials:
      - mount_path: /etc/github
        name: acm-cicd-github
        namespace: test-credentials
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ocm-ci-image-mirror
zz_generated_metadata:
  branch: release-2.9
  org: stolostron
  repo: autotune
