base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: ubi8-openjdk-11
    namespace: openshift
    tag: "1.12"
images:
- dockerfile_path: Dockerfile.autotune
  from: base
  to: autotune
promotion:
  name: "2.8"
  namespace: stolostron
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: git-fast-forward
  postsubmit: true
  steps:
    env:
      DESTINATION_BRANCH: release-2.8
    workflow: ocm-ci-fastforward
- as: pr-image-mirror
  steps:
    dependencies:
      SOURCE_IMAGE_REF: autotune
    env:
      IMAGE_REPO: autotune
      REGISTRY_ORG: stolostron
    workflow: ocm-ci-image-mirror
zz_generated_metadata:
  branch: main
  org: stolostron
  repo: autotune
